version: "3.9"

services:
  grafana:
    image: grafana/grafana:latest
    network_mode: host
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-configs:/etc/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: host
    volumes:
      - prom-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    network_mode: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.systemd'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    network_mode: host
    environment:
      - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
    command:
      - '--collector.database'
      - '--collector.database_wraparound'
      - '--collector.locks'
      - '--collector.long_running_transactions'
      - '--collector.postmaster'
      - '--collector.process_idle'
      - '--collector.replication'
      - '--collector.replication_slot'
      - '--collector.stat_activity_autovacuum'
      - '--collector.stat_bgwriter'
      - '--collector.stat_database'
      - '--collector.stat_statements'
      - '--collector.stat_user_tables'
      - '--collector.stat_wal_receiver'
      - '--collector.statio_user_indexes'
      - '--collector.statio_user_tables'
      - '--collector.wal'
      - '--collector.xlog_location'
      - '--auto-discover-databases'
      - '--log.level=info'

volumes:
  grafana-data:
  grafana-configs:
  prom-data:
  prom-configs:
